---
# need for docker build
sudo: true
dist: xenial

services:
  - docker

install:
  - sudo apt-get install jq

jobs:
  include:
    - name: multi-arch-docker-build
      arch: arm64
      script:
        - ./build.sh
