---
# need for docker build
sudo: true
dist: xenial

services:
  - docker

install:
  - sudo apt-get install jq

jobs:
  include:
    - name: multi-arch-docker-build on arm64
      arch: arm64
      script:
        - echo $DOCKER_USERNAME
        - ./build.sh arm64
    - name: multi-arch-docker-build on amd64
      arch: amd64
      script:
        - echo $DOCKER_USERNAME
        - ./build.sh amd64

deploy:
  - provider: script
    arch: arm64
    on: # yamllint disable-line rule:truthy
      all_branches: true
    script: git stash && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  && ./push.sh arm64
  - provider: script
    skip_cleanup: true
    arch: amd64
    on: # yamllint disable-line rule:truthy
      all_branches: true
    script: git stash && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  ./push.sh amd64
